server:
  port: 8090

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: author-service
          uri: lb://AUTHOR-SERVICE
          predicates:
            - Path=/author/**